server.port=8080
logging.level.web=debug
spring.messages.basename=welcome

# = Database Configuration - THÊM useGssapi=false
spring.datasource.url=jdbc:mariadb://localhost:3306/foods?useGssapi=false&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
