spring.application.name=service-order
server.port=8083

# Database Configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/service_order
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.root=INFO
logging.level.fit.se.serviceorder=DEBUG
